-- MySQL Script generated by MySQL Workbench
-- sex 20 mai 2022 02:27:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `data_de_nascimento` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `mydb`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vagas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `competencias` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `id_empresas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vagas_1_idx` (`id_empresas` ASC) VISIBLE,
  CONSTRAINT `fk_vagas_1`
    FOREIGN KEY (`id_empresas`)
    REFERENCES `mydb`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`competencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidatos_competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidatos_competencias` (
  `idcandidatos_competencias` INT NOT NULL,
  PRIMARY KEY (`idcandidatos_competencias`),
  CONSTRAINT `fk_candidatos_competencias_2`
    FOREIGN KEY (`idcandidatos_competencias`)
    REFERENCES `mydb`.`competencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidatos_competencias_1`
    FOREIGN KEY (`idcandidatos_competencias`)
    REFERENCES `mydb`.`candidatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresas_competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_competencias` (
  `idempresas_competencias` INT NOT NULL,
  PRIMARY KEY (`idempresas_competencias`),
  CONSTRAINT `fk_empresas_competencias_1`
    FOREIGN KEY (`idempresas_competencias`)
    REFERENCES `mydb`.`vagas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_competencias_2`
    FOREIGN KEY (`idempresas_competencias`)
    REFERENCES `mydb`.`competencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
